//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Core.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string OrderID { get; set; }
        public int TourID { get; set; }
        public int Quantity { get; set; }
        public string Price { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
