//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourManagement.Core.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int TourID { get; set; }
        public string Name { get; set; }
        public int Time { get; set; }
        public System.DateTime TimeStart { get; set; }
        public string PositionStart { get; set; }
        public string Content { get; set; }
        public Nullable<int> HotelID { get; set; }
        public int TransportID { get; set; }
        public int GroupID { get; set; }
        public int EmployeeID { get; set; }
        public int DestinationID { get; set; }
        public decimal Price { get; set; }
        public string Image { get; set; }
    
        public virtual Destination Destination { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Group Group { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
